function [r,phi] = Position(theta1,theta2)
%POSITION
%    [R,PHI] = POSITION(THETA1,THETA2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-May-2022 09:32:07

r = sqrt((cos(acos(sqrt((sin(theta1-pi./2.0).*(7.0./4.0e+1)+sin(theta2+pi./2.0).*(7.0./4.0e+1)).^2+abs(cos(theta1-pi./2.0).*(7.0./4.0e+1)+cos(theta2+pi./2.0).*(7.0./4.0e+1)+3.0./2.5e+1).^2).*(5.0./3.0))+atan2(sin(theta1-pi./2.0).*(-7.0./4.0e+1)-sin(theta2+pi./2.0).*(7.0./4.0e+1),abs(cos(theta1-pi./2.0).*(7.0./4.0e+1)+cos(theta2+pi./2.0).*(7.0./4.0e+1)+3.0./2.5e+1))+6.012387278395987e-2).*(-3.328470665197855e-1)+cos(theta2+pi./2.0).*(7.0./4.0e+1)+3.0./5.0e+1).^2+(sin(acos(sqrt((sin(theta1-pi./2.0).*(7.0./4.0e+1)+sin(theta2+pi./2.0).*(7.0./4.0e+1)).^2+abs(cos(theta1-pi./2.0).*(7.0./4.0e+1)+cos(theta2+pi./2.0).*(7.0./4.0e+1)+3.0./2.5e+1).^2).*(5.0./3.0))+atan2(sin(theta1-pi./2.0).*(-7.0./4.0e+1)-sin(theta2+pi./2.0).*(7.0./4.0e+1),abs(cos(theta1-pi./2.0).*(7.0./4.0e+1)+cos(theta2+pi./2.0).*(7.0./4.0e+1)+3.0./2.5e+1))+6.012387278395987e-2).*3.328470665197855e-1+sin(theta2+pi./2.0).*(7.0./4.0e+1)).^2);
if nargout > 1
    phi = pi./2.0-angle(cos(acos(sqrt((sin(theta1-pi./2.0).*(7.0./4.0e+1)+sin(theta2+pi./2.0).*(7.0./4.0e+1)).^2+abs(cos(theta1-pi./2.0).*(7.0./4.0e+1)+cos(theta2+pi./2.0).*(7.0./4.0e+1)+3.0./2.5e+1).^2).*(5.0./3.0))+atan2(sin(theta1-pi./2.0).*(-7.0./4.0e+1)-sin(theta2+pi./2.0).*(7.0./4.0e+1),abs(cos(theta1-pi./2.0).*(7.0./4.0e+1)+cos(theta2+pi./2.0).*(7.0./4.0e+1)+3.0./2.5e+1))+6.012387278395987e-2).*(-3.328470665197855e-1)+sin(acos(sqrt((sin(theta1-pi./2.0).*(7.0./4.0e+1)+sin(theta2+pi./2.0).*(7.0./4.0e+1)).^2+abs(cos(theta1-pi./2.0).*(7.0./4.0e+1)+cos(theta2+pi./2.0).*(7.0./4.0e+1)+3.0./2.5e+1).^2).*(5.0./3.0))+atan2(sin(theta1-pi./2.0).*(-7.0./4.0e+1)-sin(theta2+pi./2.0).*(7.0./4.0e+1),abs(cos(theta1-pi./2.0).*(7.0./4.0e+1)+cos(theta2+pi./2.0).*(7.0./4.0e+1)+3.0./2.5e+1))+6.012387278395987e-2).*3.328470665197855e-1i+cos(theta2+pi./2.0).*(7.0./4.0e+1)+sin(theta2+pi./2.0).*1.75e-1i+3.0./5.0e+1);
end
